# Generated by Django 4.1.6 on 2023-02-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marko', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderItem',
        ),
    ]
